### ISSUE TITLE
toV3 / toV3String extremely slow and intensive

### ISSUE THREAD

**Issue by ghost** [ethereumjs/browser-builds#2]
I haven't done extensive testing but the few calls I've made with toV3("pass") and toV3String("pass") all bring the CPU to 100% for about 30 seconds. I feel that may be abnormally high and hope it can be resolved. The code I run:

var wallet1 = EthJS.Wallet.generate();
var save = a.toV3String("pass"); // takes 12-20 seconds about, and brings cpu to 100%
// and also
var wallet2 = EthJS.Wallet.fromV3(save,"pass"); // same symptoms

Is there any other way to load/save a wallet as a string? The sluggishness of this will limit applications.

thanks.

**Comment by axic** [comment]
`toV3` users `scrypt` for derivation with the settings suggested by the specification (the same as used by `geth`).

Unfortunately by design this is a resource intensive operation. That part of the code, when used in browsers, should be done via a [web worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers).

**Comment by ghost** [comment]
Thanks axic for the suggestion! I'll test it with a web worker and close this issue soon.
